services:
  db:
    image: postgres:14.18
    env_file: .env
    restart: always

  api:
    build: .
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always

  worker:
    build: .
    command: node worker
    restart: always
    depends_on:
      - redis
